'rpsl' import;
"Testing file input..." println;
test_input_without_blank.txt f<; gen var; gen !;
"File opened successfully" println;
gen @; rpsl.parsem; result var; result !;
"rpsl.parsem completed" println;
result @; shift; first var; first !;
"First object retrieved" println;
first @; str;
"First object displayed" println;
result @; shift; second var; second !;
"Second object retrieved" println;
second @; str;
"Second object displayed" println;